parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection:     centrale_produits
        connections:
            centrale_produits:
                driver_class:   Lsw\DoctrinePdoDblib\Doctrine\DBAL\Driver\PDODblib\Driver
                host:         "185.29.149.144"
                user:         "AC_JBAGOSTIN"
                password:     "35H7Hjvy"
                dbname:       "CENTRALE_PRODUITS"
                charset:  UTF-8
                options:
                    ansi_nulls: on
                    ansi_warnings: on
                    20: false
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:  centrale_produits
        entity_managers:
            centrale_produits:
                connection: centrale_produits